### ISSUE TITLE
About comments in css

### ISSUE THREAD

**Issue by braver** [ninteddie/trunk#2]
I see a type of comment in your stylesheets that apparently are almost like a standard here at Peppered, but they're really a bad practice. I like how you clearly segment your stylesheet with comments, but there are a number of comments that are almost impossible to maintain over the lifetime of the stylesheet and don't really add any information.

One of them is these:

```
/* header */
#header {
    width: 100%;
    height: $headerHeight;
    position: fixed;
    background-color: $colorGrayScaleG;
    z-index: 2;
}
```

I can already see that the header is going to be styled, #header gives that away :) Especially as your stylesheet grows, it's totally unclear when that header section ends. And it doesn't matter, because it isn't necessarily true that the elements styled in that section only occur in the #header.

Just let the stylesheet speak for itself. Just like you did with the #footer, you can use nesting in SASS to maintain the correct specificity and make your stylesheet more readable at the same time.

The other is the list of sections at the top of the stylesheet:

```
// Brugge variables
//
// -Required
// -General
// -Layout
// -Fonts
// -Colors
// -Icons
// -Helpers
```

This list isn't going to maintain itself. And really, it should already be clear what's in your stylesheet. A list such as this doesn't add any clarity at all for anyone but you, and so really has no purpose.

Recommended reading: http://visualstudiomagazine.com/articles/2013/06/01/roc-rocks.aspx

**Comment by ninteddie** [comment]
Thanks for the tip, I will put this into practice =)
